### PR TITLE
Support modern active record, Factory.build

### PR DESCRIPTION
**Pull request by bwthomas**
See title. Let me know if further detail is desired & I'll update the PR.

### CODE REVIEW

**Comment by marnen** [comment]
Any idea when this will be released?

**Comment by chewi** [comment]
I will try to make a release next week. I want to check something first.

**Comment by marnen** [comment]
OK. I'm using this as a GitHub ref in my project and it seems to work.

**Comment by chewi** [comment]
Done. :smiley_cat:

**Pull request closed without merging**
