### PR TITLE
Make Travis happy, all recent rubies, Rails 4.2.9

### PR DESCRIPTION
**Pull request by mathieujobin**
here is a start, I've added recent rubies and replace the 3.1 rails by a 4.2.6

not every tests pass, but it's a start.

in a different branch, I tried to replace the `alias_method_chain` by `Module#prepend`

### CODE REVIEW

**Comment by mathieujobin** [comment]
travis build https://travis-ci.org/venuenext/pickle/builds/129770631

**Comment by mathieujobin** [comment]
is this still maintained ? should we replace pickle by something better in our applications?

**Comment by chewi** [comment]
Not really. I gave it a good shot in the arm a while back but that ended up going beyond what I needed for my day job and I have plenty of more interesting open source responsibilities elsewhere. We still use it and it still works, surprisingly enough. I suppose it doesn't get a lot of attention because the approach is generally frowned upon by the Cucumber community.

**Comment by mathieujobin** [comment]
thanks for the reply @chewi 

I'll wait to see if more interest shows for this
and I might continue to get tests to pass with rails 4.2 and 5

**Comment by chewi** [comment]
For what it's worth, we use it with 4.2.7.1. Just because the tests don't work doesn't mean it doesn't work in practise. :wink:

**Comment by mathieujobin** [comment]
works for us as well, but it would be nice to replace the deprecation on `alias_method_chain`

**Comment by mathieujobin** [comment]
this is the failures I have left... if anyone would like to help and figure it out...
```
Failing Scenarios:
cucumber features/email/email.feature:6 # Scenario: Deliver an email, and test it's properties
cucumber features/email/email.feature:14 # Scenario: Deliver some emails, restrict scope
cucumber features/email/email.feature:34 # Scenario: Deliver emails to user
cucumber features/email/email.feature:41 # Scenario: Following the first link in an email
cucumber features/email/email.feature:48 # Scenario: Following a link in an email by url
cucumber features/email/email.feature:55 # Scenario: Following a link in an email by the text
cucumber features/generator/generators.feature:7 # Scenario: script/generate pickle on fresh cuke install
cucumber features/generator/generators.feature:14 # Scenario: script/generate pickle path on fresh cuke install
cucumber features/generator/generators.feature:23 # Scenario: script/generate pickle email on fresh cuke install
cucumber features/generator/generators.feature:33 # Scenario: script/generate pickle path email on fresh cuke install
cucumber features/generator/generators.feature:46 # Scenario: regenerating pickle

45 scenarios (11 failed, 34 passed)
240 steps (11 failed, 46 skipped, 183 passed)
0m12.236s
```

**Comment by mathieujobin** [comment]
finally, we got travis running tests again... 

@ianwhite can you make me admin of the repo, so I can protect the master branch against merge that don't have tests passing ?

**Pull request merged**
